name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '11 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl 'https://citizen.com/api/incident/trending?lowerLatitude=44.779284867425446&lowerLongitude=-94.07216505086762&upperLatitude=45.16623243507959&upperLongitude=-92.45628094913246&fullResponse=true&limit=50' | jq . > incidents.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
